# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.7"

# Define services
services:
  db:
    image: mysql:5.6
    ports:
      - 13306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
    volumes:
      - .:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    networks:
      - backend
  # App backend service
  server:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the app directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    # restart: always
    volumes:
      - .:/usr/app
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
      DB_HOST: db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

# Volumes

volumes:
  dbdata:
# Networks to be created to facilitate communication between containers
networks:
  backend: